# Generated by Django 2.0.7 on 2018-07-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_id', models.IntegerField()),
                ('pizza_size', models.CharField(choices=[('M', '30 cm'), ('L', '50 cm')], max_length=1)),
                ('customer_name', models.CharField(max_length=140)),
                ('customer_address', models.TextField()),
            ],
        ),
    ]
