# Generated by Django 2.0.7 on 2018-07-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pizza_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
